// <auto-generated />
namespace ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class correctionGlobal4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correctionGlobal4));
        
        string IMigrationMetadata.Id
        {
            get { return "201505061541448_correctionGlobal4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
